library(shiny)
library(shinyjs)
library(plotly)
library(ggplot2)
library(RColorBrewer)
library(mongolite)
library(jsonlite)
library(BiocParallel)
library(sp)
library(Cardinal)
library(dplyr)
library(png)
library(jpeg)
library(vsclust)
library(matrixStats)
library(caret)
library(ranger)
library(MLmetrics)
library(DT)
library(pROC)
library(scales)

source("global.R")

shinyApp(ui = ui, server = server)
