library(shiny)
library(shinyjs)
library(plotly)
library(ggplot2)
library(RColorBrewer)
library(mongolite)
library(uuid)
library(jsonlite)
library(BiocParallel)
library(sp)
library(Cardinal)
library(dplyr)
library(png)
library(jpeg)
library(vsclust)
library(matrixStats)

source("global.R")

shinyApp(ui = ui, server = server)
