# R/modules/welcome_module.R

welcome_module_ui <- function(id) {
  ns <- NS(id)

  tabPanel(
    "Welcome",

    div(class = "welcome-container",

      h1("MSI Clustering & Prediction Platform"),

      p(
        class = "lead",
        "An interactive workflow for analysing Mass Spectrometry Imaging (MSI) data."
      ),

      br(),

      # WORKFLOW CARDS
      fluidRow(

        column(
          3,
          div(
            class = "welcome-card",
            h4("1. Processing"),
            icon("cogs", "fa-2x"),
            p("Convert raw MSI data into feature matrices."),
            actionButton(ns("show_processing"), "Learn more")
          )
        ),

        column(
          3,
          div(
            class = "welcome-card",
            h4("2. Clustering"),
            icon("project-diagram", "fa-2x"),
            p("Explore spatial clusters and assign labels."),
            actionButton(ns("show_clustering"), "Learn more")
          )
        ),

        column(
          3,
          div(
            class = "welcome-card",
            h4("3. Training"),
            icon("brain", "fa-2x"),
            p("Train machine learning models."),
            actionButton(ns("show_training"), "Learn more")
          )
        ),

        column(
          3,
          div(
            class = "welcome-card",
            h4("4. Prediction"),
            icon("chart-line", "fa-2x"),
            p("Predict tissue classes in new data."),
            actionButton(ns("show_prediction"), "Learn more")
          )
        )
      ),

      br(),

      # INTERACTIVE DETAILS RIGHT UNDER THE CARDS
      uiOutput(ns("details")),

      br(),

      h3("Data Objects in the Platform"),

      tags$img(
        src = "workflow_diagram.png",
        style = "width:100%; max-width:900px; display:block; margin:0 auto 15px auto;"
      ),

      p(
        "All analysis steps store structured objects in the database to ensure reproducibility."
      ),

      br(),

      fluidRow(
        column(
          4,
          div(
            class = "welcome-detail-box",
            h4("Study"),
            p("A top-level container representing a project or dataset collection.")
          ),
          div(
            class = "welcome-detail-box",
            h4("Sample"),
            p("An individual MSI experiment belonging to a study.")
          ),
          div(
            class = "welcome-detail-box",
            h4("Pipeline"),
            p("A versioned parameter configuration describing how a processing or clustering step was performed.")
          )
        ),

        column(
          4,
          div(
            class = "welcome-detail-box",
            h4("Artifact"),
            p("A stored output generated by a pipeline, such as a processed feature matrix.")
          ),
          div(
            class = "welcome-detail-box",
            h4("Annotation Set"),
            p("A set of possible class labels that can be assigned to pixels or regions.")
          ),
          div(
            class = "welcome-detail-box",
            h4("Annotation"),
            p("The actual assignment of labels to specific pixels or regions within a sample.")
          )
        ),

        column(
          4,
          div(
            class = "welcome-detail-box",
            h4("Dataset"),
            p("A frozen snapshot combining samples, processed data, annotations, and train/test split settings.")
          ),
          div(
            class = "welcome-detail-box",
            h4("Model Run"),
            p("A trained machine learning model together with hyperparameters and evaluation metrics.")
          )
        )
      )
    )
  )
}


welcome_module_server <- function(id) {
  moduleServer(id, function(input, output, session) {

    active_panel <- reactiveVal("intro")

    observeEvent(input$show_processing, {
      active_panel("processing")
    })

    observeEvent(input$show_clustering, {
      active_panel("clustering")
    })

    observeEvent(input$show_training, {
      active_panel("training")
    })

    observeEvent(input$show_prediction, {
      active_panel("prediction")
    })

    output$details <- renderUI({
      panel <- active_panel()

      if (panel == "processing") {
        return(
          div(
            class = "welcome-detail-box",
            h4("Processing"),
            p("Raw imzML and ibd files are converted into pixel-level feature matrices using a configurable processing pipeline."),
            p(strong("Main stored objects: "), "Study, Sample, Pipeline, and Artifact."),
            p(strong("Main output: "), "A binned_dataframe artifact used for clustering and downstream model training.")
          )
        )
      }

      if (panel == "clustering") {
        return(
          div(
            class = "welcome-detail-box",
            h4("Clustering"),
            p("Processed MSI features are clustered to identify spatial patterns and tissue structure."),
            p("Users can inspect results and assign biologically meaningful labels."),
            p(strong("Main stored objects: "), "Clustering pipeline, clustering artifact, annotation set, and annotations.")
          )
        )
      }

      if (panel == "training") {
        return(
          div(
            class = "welcome-detail-box",
            h4("Training"),
            p("Frozen datasets combine selected samples, processing outputs, annotation labels, and split settings into a reproducible training input."),
            p("Machine learning models are trained and stored together with hyperparameters and evaluation metrics."),
            p(strong("Main stored objects: "), "Dataset and Model Run.")
          )
        )
      }

      if (panel == "prediction") {
        return(
          div(
            class = "welcome-detail-box",
            h4("Prediction"),
            p("Trained models can be applied to new MSI data to generate predicted labels."),
            p("This module is intended for inference on unseen samples and comparison of prediction results.")
          )
        )
      }

      div(
        class = "welcome-detail-box",
        h4("Get started"),
        p("Click one of the workflow cards above to learn more about each module."),
        p("A typical workflow is:"),
        tags$ol(
          tags$li("Process raw MSI data"),
          tags$li("Cluster pixels and assign labels"),
          tags$li("Create a frozen dataset"),
          tags$li("Train and compare models"),
          tags$li("Apply trained models to new data")
        )
      )
    })
  })
}